version: '3.8'

services:
  api:
    build: ./
    container_name: home-library-service
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
    networks:
      - my_network

  postgres:
    image: postgres:16-alpine
    container_name: home-library-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${PORT_DB}:${PORT_DB}'
    volumes:
      - home-library-postgres:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  home-library-postgres:

networks:
  my_network:
    driver: bridge
